# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: porsit_chatbot/grpc_server/protos/models.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'porsit_chatbot/grpc_server/protos/models.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.porsit_chatbot/grpc_server/protos/models.proto\"4\n\x0eIntentResponse\x12\x0e\n\x06intent\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\"B\n\x06\x45ntity\x12\x0c\n\x04word\x18\x01 \x01(\t\x12\x0e\n\x06\x65ntity\x18\x02 \x01(\t\x12\r\n\x05start\x18\x03 \x01(\x05\x12\x0b\n\x03\x65nd\x18\x04 \x01(\x05\"+\n\x0e\x45ntityResponse\x12\x19\n\x08\x65ntities\x18\x01 \x03(\x0b\x32\x07.Entity\"]\n\x0fGenerateRequest\x12\x0f\n\x07\x63ontext\x18\x01 \x01(\t\x12\x0e\n\x06prompt\x18\x02 \x01(\t\x12\x14\n\x0cmodel_choice\x18\x03 \x01(\t\x12\x13\n\x0b\x63lient_name\x18\x04 \x01(\t\"$\n\x10GenerateResponse\x12\x10\n\x08response\x18\x01 \x01(\t\"E\n\x10SummarizeRequest\x12\x1c\n\x14\x63onversation_history\x18\x01 \x01(\t\x12\x13\n\x0b\x63lient_name\x18\x02 \x01(\t\"\"\n\x12\x43lassifyAllRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"T\n\x11\x43lassifyRequestLC\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x1c\n\x14\x63onversation_history\x18\x02 \x01(\t\x12\x13\n\x0b\x63lient_name\x18\x03 \x01(\t\"f\n\x10\x43ombinedResponse\x12(\n\x0fintent_response\x18\x01 \x01(\x0b\x32\x0f.IntentResponse\x12(\n\x0f\x65ntity_response\x18\x02 \x01(\x0b\x32\x0f.EntityResponse2\xf1\x01\n\x0cModelService\x12\x32\n\x0bLLMResponse\x12\x10.GenerateRequest\x1a\x11.GenerateResponse\x12=\n\x15SummarizeConversation\x12\x11.SummarizeRequest\x1a\x11.GenerateResponse\x12\x35\n\x0b\x43lassifyAll\x12\x13.ClassifyAllRequest\x1a\x11.CombinedResponse\x12\x37\n\x0e\x43lassifyAll_LC\x12\x12.ClassifyRequestLC\x1a\x11.CombinedResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'porsit_chatbot.grpc_server.protos.models_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INTENTRESPONSE']._serialized_start=50
  _globals['_INTENTRESPONSE']._serialized_end=102
  _globals['_ENTITY']._serialized_start=104
  _globals['_ENTITY']._serialized_end=170
  _globals['_ENTITYRESPONSE']._serialized_start=172
  _globals['_ENTITYRESPONSE']._serialized_end=215
  _globals['_GENERATEREQUEST']._serialized_start=217
  _globals['_GENERATEREQUEST']._serialized_end=310
  _globals['_GENERATERESPONSE']._serialized_start=312
  _globals['_GENERATERESPONSE']._serialized_end=348
  _globals['_SUMMARIZEREQUEST']._serialized_start=350
  _globals['_SUMMARIZEREQUEST']._serialized_end=419
  _globals['_CLASSIFYALLREQUEST']._serialized_start=421
  _globals['_CLASSIFYALLREQUEST']._serialized_end=455
  _globals['_CLASSIFYREQUESTLC']._serialized_start=457
  _globals['_CLASSIFYREQUESTLC']._serialized_end=541
  _globals['_COMBINEDRESPONSE']._serialized_start=543
  _globals['_COMBINEDRESPONSE']._serialized_end=645
  _globals['_MODELSERVICE']._serialized_start=648
  _globals['_MODELSERVICE']._serialized_end=889
# @@protoc_insertion_point(module_scope)
