# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from porsit_chatbot.grpc_server.protos import models_pb2 as porsit__chatbot_dot_grpc__server_dot_protos_dot_models__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in porsit_chatbot/grpc_server/protos/models_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ModelServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LLMResponse = channel.unary_unary(
                '/ModelService/LLMResponse',
                request_serializer=porsit__chatbot_dot_grpc__server_dot_protos_dot_models__pb2.GenerateRequest.SerializeToString,
                response_deserializer=porsit__chatbot_dot_grpc__server_dot_protos_dot_models__pb2.GenerateResponse.FromString,
                _registered_method=True)
        self.SummarizeConversation = channel.unary_unary(
                '/ModelService/SummarizeConversation',
                request_serializer=porsit__chatbot_dot_grpc__server_dot_protos_dot_models__pb2.SummarizeRequest.SerializeToString,
                response_deserializer=porsit__chatbot_dot_grpc__server_dot_protos_dot_models__pb2.GenerateResponse.FromString,
                _registered_method=True)
        self.ClassifyAll = channel.unary_unary(
                '/ModelService/ClassifyAll',
                request_serializer=porsit__chatbot_dot_grpc__server_dot_protos_dot_models__pb2.ClassifyAllRequest.SerializeToString,
                response_deserializer=porsit__chatbot_dot_grpc__server_dot_protos_dot_models__pb2.CombinedResponse.FromString,
                _registered_method=True)
        self.ClassifyAll_LC = channel.unary_unary(
                '/ModelService/ClassifyAll_LC',
                request_serializer=porsit__chatbot_dot_grpc__server_dot_protos_dot_models__pb2.ClassifyRequestLC.SerializeToString,
                response_deserializer=porsit__chatbot_dot_grpc__server_dot_protos_dot_models__pb2.CombinedResponse.FromString,
                _registered_method=True)


class ModelServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def LLMResponse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SummarizeConversation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClassifyAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClassifyAll_LC(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LLMResponse': grpc.unary_unary_rpc_method_handler(
                    servicer.LLMResponse,
                    request_deserializer=porsit__chatbot_dot_grpc__server_dot_protos_dot_models__pb2.GenerateRequest.FromString,
                    response_serializer=porsit__chatbot_dot_grpc__server_dot_protos_dot_models__pb2.GenerateResponse.SerializeToString,
            ),
            'SummarizeConversation': grpc.unary_unary_rpc_method_handler(
                    servicer.SummarizeConversation,
                    request_deserializer=porsit__chatbot_dot_grpc__server_dot_protos_dot_models__pb2.SummarizeRequest.FromString,
                    response_serializer=porsit__chatbot_dot_grpc__server_dot_protos_dot_models__pb2.GenerateResponse.SerializeToString,
            ),
            'ClassifyAll': grpc.unary_unary_rpc_method_handler(
                    servicer.ClassifyAll,
                    request_deserializer=porsit__chatbot_dot_grpc__server_dot_protos_dot_models__pb2.ClassifyAllRequest.FromString,
                    response_serializer=porsit__chatbot_dot_grpc__server_dot_protos_dot_models__pb2.CombinedResponse.SerializeToString,
            ),
            'ClassifyAll_LC': grpc.unary_unary_rpc_method_handler(
                    servicer.ClassifyAll_LC,
                    request_deserializer=porsit__chatbot_dot_grpc__server_dot_protos_dot_models__pb2.ClassifyRequestLC.FromString,
                    response_serializer=porsit__chatbot_dot_grpc__server_dot_protos_dot_models__pb2.CombinedResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ModelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ModelService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ModelService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def LLMResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ModelService/LLMResponse',
            porsit__chatbot_dot_grpc__server_dot_protos_dot_models__pb2.GenerateRequest.SerializeToString,
            porsit__chatbot_dot_grpc__server_dot_protos_dot_models__pb2.GenerateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SummarizeConversation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ModelService/SummarizeConversation',
            porsit__chatbot_dot_grpc__server_dot_protos_dot_models__pb2.SummarizeRequest.SerializeToString,
            porsit__chatbot_dot_grpc__server_dot_protos_dot_models__pb2.GenerateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClassifyAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ModelService/ClassifyAll',
            porsit__chatbot_dot_grpc__server_dot_protos_dot_models__pb2.ClassifyAllRequest.SerializeToString,
            porsit__chatbot_dot_grpc__server_dot_protos_dot_models__pb2.CombinedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClassifyAll_LC(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ModelService/ClassifyAll_LC',
            porsit__chatbot_dot_grpc__server_dot_protos_dot_models__pb2.ClassifyRequestLC.SerializeToString,
            porsit__chatbot_dot_grpc__server_dot_protos_dot_models__pb2.CombinedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
